# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uiit1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog
import os
import re

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.pictureCon = QtWidgets.QLabel(self.centralwidget)
        # self.pictureCon.setGeometry(QtCore.QRect(0, 0, 1890, 1000))
        self.pictureCon.setGeometry(QtCore.QRect(0, 0, 1890, 1000))
        self.pictureCon.setText("")
        self.pictureCon.setPixmap(QtGui.QPixmap("apple.jpg"))
        self.pictureCon.setScaledContents(True)
        self.pictureCon.setObjectName("pictureCon")
        self.pictureCon.setAlignment(QtCore.Qt.AlignCenter)

        self.backButton = QtWidgets.QPushButton(self.centralwidget)
        self.backButton.setGeometry(QtCore.QRect(10, 380, 50, 160))
        self.backButton.setObjectName("backButton")


        self.forewardButton = QtWidgets.QPushButton(self.centralwidget)
        self.forewardButton.setGeometry(QtCore.QRect(1860, 380, 50, 160))
        self.forewardButton.setObjectName("forewardButton")

        self.scale = .8
        self.width = 1890
        self.hight = 1000
        self.zoomInButton = QtWidgets.QPushButton(self.centralwidget)
        self.zoomInButton.setGeometry(QtCore.QRect(0, 0, 50, 160))
        self.zoomInButton.setObjectName("zoomInButton")
        self.zoomInButton.setText("zoom in")
        self.zoomInButton.clicked.connect(lambda: self.zoom(int(1)))

        self.zoomOutButton = QtWidgets.QPushButton(self.centralwidget)
        self.zoomOutButton.setGeometry(QtCore.QRect(100, 320, 50, 160))
        self.zoomOutButton.setObjectName("zoomOutButton")
        self.zoomOutButton.setText("zoom out")
        self.zoomOutButton.clicked.connect(lambda: self.zoom(int(0)))

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 891, 21))
        self.menubar.setObjectName("menubar")
        self.menuFIle = QtWidgets.QMenu(self.menubar)
        self.menuFIle.setObjectName("menuFIle")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.menuFIle.addAction(self.actionOpen)
        self.menubar.addAction(self.menuFIle.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.backButton.clicked.connect(self.backButtonAction)
        self.forewardButton.clicked.connect(self.forwardButtonAction)
        self.actionOpen.triggered.connect(self.openButtonHandler)
        self.piclistcount = 0
        self.pics = [x for x in os.listdir() if re.match(".*[.]jpg", x)]



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.backButton.setText(_translate("MainWindow", "back"))
        self.forewardButton.setText(_translate("MainWindow", "forward"))
        self.menuFIle.setTitle(_translate("MainWindow", "File"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
    
    def forwardButtonAction(self):
        self.piclistcount = self.piclistcount + 1 if self.piclistcount + 1 < len(self.pics) else 0
        self.pictureCon.setPixmap(QtGui.QPixmap(self.pics[self.piclistcount]))
        print(self.piclistcount)
    
    def backButtonAction(self):
        self.piclistcount = self.piclistcount - 1 if self.piclistcount - 1 >= 0 else len(self.pics) - 1
        self.pictureCon.setPixmap(QtGui.QPixmap(self.pics[self.piclistcount]))
        print(self.piclistcount)

    def openButtonHandler(self):
        filename = QFileDialog.getOpenFileName()[0]
        self.pictureCon.setPixmap(QtGui.QPixmap(filename))
        print(filename)
        filepath = re.match(".+\/", filename).group(0)
        self.pics = [filepath + x for x in os.listdir(filepath) if re.match(".*[.]jpg||.*[.]png", x)]
        self.piclistcount = self.pics.index(filename)
    
    def zoom(self, num):
        nwidth = (num + self.scale) * self.width
        nhight = (num + self.scale) * self.hight
        self.pictureCon.resize(nwidth, nhight)
        self.width = nwidth
        self.hight = nhight

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
