# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uiit1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
import re

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pictureCon = QtWidgets.QLabel(self.centralwidget)
        self.pictureCon.setGeometry(QtCore.QRect(70, 20, 751, 621))
        self.pictureCon.setText("")
        self.pictureCon.setPixmap(QtGui.QPixmap("apple.jpg"))
        self.pictureCon.setScaledContents(True)
        self.pictureCon.setObjectName("pictureCon")
        self.backButton = QtWidgets.QPushButton(self.centralwidget)
        self.backButton.setGeometry(QtCore.QRect(10, 230, 51, 141))
        self.backButton.setObjectName("backButton")
        self.forewardButton = QtWidgets.QPushButton(self.centralwidget)
        self.forewardButton.setGeometry(QtCore.QRect(830, 230, 51, 151))
        self.forewardButton.setObjectName("forewardButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 891, 21))
        self.menubar.setObjectName("menubar")
        self.menuFIle = QtWidgets.QMenu(self.menubar)
        self.menuFIle.setObjectName("menuFIle")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFIle.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.backButton.clicked.connect(self.nextButton)
        self.forewardButton.clicked.connect(self.nextButton)
        self.piclistcount = 0
        self.pics = [x for x in os.listdir() if re.match(".*[.]jpg", x)]


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.backButton.setText(_translate("MainWindow", "back"))
        self.forewardButton.setText(_translate("MainWindow", "forward"))
        self.menuFIle.setTitle(_translate("MainWindow", "File"))
    
    def nextButton(self):
        self.pictureCon.setPixmap(QtGui.QPixmap(self.pics[self.piclistcount]))
        self.piclistcount = self.piclistcount + 1 if self.piclistcount + 1 < len(self.pics) else 0




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
